### PR TITLE
Feature/createnewdataset

### PR DESCRIPTION
**Pull request by thomasdegroot18**

### CODE REVIEW

**Comment by MPvHarmelen** [comment]
Nice cleaning! However, I noticed that you removed `dataset-settings-page.png`, even though it's used in the `index.md` line 182: https://github.com/TriplyDB/Documentation/search?q=dataset-settings-page

**Comment by MPvHarmelen** [comment]
Same goes for `upload-error.png`: https://github.com/TriplyDB/Documentation/search?q=upload-error

**Review by MPvHarmelen — CHANGES_REQUESTED** [review]
See above comments.

**Comment by thomasdegroot18** [comment]
@MPvHarmelen That is strange, I do see both of images in de directory.  https://github.com/TriplyDB/Documentation/tree/feature/createnewdataset/docs/triply-db
 - https://github.com/TriplyDB/Documentation/blob/feature/createnewdataset/docs/triply-db/dataset-settings-page.png
  - https://github.com/TriplyDB/Documentation/blob/feature/createnewdataset/docs/triply-db/upload-error.png

**Pull request merged**
